package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.SshAgent
import jetbrains.buildServer.configs.kotlin.buildFeatures.sshAgent
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'GradleJib'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("GradleJib")) {
    features {
        val feature1 = find<SshAgent> {
            sshAgent {
                teamcitySshKey = "teamcity_github_rsa"
                passphrase = "%github.ssh.passphrase%"
            }
        }
        feature1.apply {
            passphrase = "credentialsJSON:f8ca046c-1539-4611-a146-c578411e5f91"
        }
    }
}
