--liquibase formatted sql

--changeset elhub:40
GRANT USAGE ON SCHEMA auth_v1 TO ${APP_USERNAME};

GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA auth_v1 TO ${APP_USERNAME};

ALTER DEFAULT PRIVILEGES IN SCHEMA auth_v1
    GRANT SELECT, INSERT, UPDATE ON TABLES TO ${APP_USERNAME};
