@startuml context-diagram
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(EndUser, "End User", "A person in the public power market.")
System(MarketParty, "Market Party", "The initiating system controlled by an organization participating in the power market.")
System_Boundary(elhub, "Elhub") {
  System(EMIF, "Elhub Machine Interface", "EMIF is the legacy interface for sending/receiving business processes to Elhub.")
  System(ConsentManager, "Consent Manager", "The consent manager handles registration and storage of consent data in Elhub.")
  System(MyPage, "MinSide", "Minside provides the user interface for End Users that need to interact with Elhub.")
}

' Relationships
Rel(MarketParty, ConsentManager, "Documents/Consent Requests", "HTTPS/JSON")
Rel(MarketParty, EMIF, "Business processes", "HTTPS/SOAP")
Rel(MarketParty, MyPage, "Web/App Redirect", "HTTPS/HTML")
Rel(EMIF, ConsentManager, "Validates", "HTTPS/JSON")
Rel(MyPage, ConsentManager, "Uses", "HTTPS/JSON")
Rel(EndUser, MarketParty, "Interacts with market party")
Rel(EndUser, MyPage, "Grants/Administrates Consent", "HTTPS/HTML")

SHOW_LEGEND()
@enduml
