@startuml datamodel

' The PartyId is a type that is used to identify a party
' It can be an elhub user Id or a GLN. It is a string because it can be a UUID or a GLN-number
' type PartyId = String

abstract Party {
  + id: PartyId
  --
  + name: String
  + type: Enum (person, organization)
}

entity Person {
  + id: PartyId
  --
  + firstName: String
  + lastName: String
  + dateOfBirth: Date
}

entity Organization {
  + id: PartyId
  --
  + name: String
}

enum AuthorizationGrantStatus {
  Active
  Exhausted
  Expired
  Revoked
}

enum AuthorizationResource {
  MeteringPoint
  Organization
  Person
}

enum PermissionType {
  ChangeOfSupplier
  FullDelegation
  ReadAccess
}

enum AuthorizationDocumentStatus {
  Expired
  Pending
  Rejected
  Signed
}

enum AuthorizationRequestStatus {
  Accepted
  Expired
  Pending
  Rejected
}

enum DocumentType {
  ChangeOfSupplierConfirmation
}

enum RequestType {
  ChangeOfSupplierConfirmation
}

entity AuthorizationGrant {
  id: UUID
  --
  status: AuthorizationGrantStatus
  grantedFor: PartyId, FK→Party
  grantedBy: PartyId, FK→Party
  grantedTo: PartyId, FK→Party
  grantedAt: DateTime
  validFrom: DateTime
  validTo: DateTime
}

' Used to store metadata related to the AuthorizationGrant
entity AuthorizationGrantProperty {
  authorizationGrantId: UUID, FK→AuthorizationGrant
  key: String
  --
  value: String
}

entity AuthorizationAuditLog {
  authorizationGrantId: UUID, FK->AuthorizationGrant
  changedAt: DateTime
  --
  changedBy: PartyId, FK->Party
  valueChanged: String
  valueBefore: String
  valueAfter: String
  message: String
}

entity AuthorizationRequest {
  id: UUID
  --
  type: RequestType
  status: AuthorizationRequestStatus
  requestedBy: PartyId, FK→Party
  requestedTo: PartyId, FK→Party
  createdAt: DateTime
  validTo: DateTime
}

entity AuthorizationRequestProperty {
  authorizationRequestId: UUID, FK→AuthorizationRequest
  key: String
  --
  value: String
}

' In this model it is assumed that the metadata is stored in the document.
entity AuthorizationDocument {
  id: UUID
  --
  title: String
  type: DocumentType
  file: Blob
  status: AuthorizationDocumentStatus
  requestedBy: PartyId, FK→Party
  createdAt: DateTime
  updatedAt: DateTime
}

entity AuthorizationDocumentSignatories {
  authorizationDocumentId: UUID, FK→Document
  requestedTo: PartyId, FK→Party
  --
  signedBy: PartyId, FK→Person
  signedAt: DateTime
}

entity AuthorizationGrantScope {
  authorizationGrantId: UUID, FK→AuthorizationGrant
  authorizationScopeId: BigInt, FK→AuthorizationScope
  --
  createdAt: DateTime
}

entity AuthorizationDocumentScope {
  authorizationDocumentId: UUID, FK→AuthorizationDocument
  authorizationScopeId: BigInt, FK→AuthorizationScope
  --
  createdAt: DateTime
}

entity AuthorizationRequestScope {
  authorizationRequestId: UUID, FK→AuthorizationRequest
  authorizationScopeId: BigInt, FK→AuthorizationScope
  --
  createdAt: DateTime
}

entity AuthorizationScope {
  id: BigSerial
  authorizedResourceType: AuthorizationResource
  authorizedResourceId: String
  permissionType: PermissionType
  --
  createdAt: DateTime
}

' Relationships
Party <|-- Person
Party <|-- Organization
AuthorizationGrant *-- AuthorizationGrantProperty
AuthorizationGrant *-- AuthorizationGrantScope
AuthorizationGrant *-- AuthorizationAuditLog
AuthorizationGrant -- AuthorizationSource
AuthorizationGrant -- AuthorizationGrantStatus
AuthorizationGrant --> Party
AuthorizationScope -- AuthorizationResource
AuthorizationScope -- PermissionType
AuthorizationScope -- AuthorizationGrantScope
AuthorizationScope -- AuthorizationRequestScope
AuthorizationScope -- AuthorizationDocumentScope
AuthorizationDocument *-- AuthorizationDocumentSignatories
AuthorizationDocument *-- AuthorizationDocumentScope
AuthorizationDocument -- DocumentType
AuthorizationDocument -- AuthorizationDocumentStatus
AuthorizationDocument --> Party
AuthorizationDocumentSignatories -> Party
AuthorizationDocumentSignatories --> Person
AuthorizationRequest *-- AuthorizationRequestProperty
AuthorizationRequest *-- AuthorizationRequestScope
AuthorizationRequest -- RequestType
AuthorizationRequest -- AuthorizationRequestStatus

@enduml
