@startuml document-flow
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Sequence.puml

Person_Ext(EndUser, "End User", "")
System_Ext(MarketParty, "Market Party", "")

System_Boundary(Elhub, "Elhub")
  System(GrantManager, "auth-grant-manager", "")
  System(EMIF, "EMIF", "")
Boundary_End()

System_Boundary(SignatureProvider, "Signature Provider")
  System_Ext(SigningService, "Signing Service", "")
Boundary_End()

activate EndUser
Rel(EndUser, MarketParty, "Interacts with market party ")
Rel(MarketParty, GrantManager, "POST /authorization-documents ")
Rel(GrantManager, GrantManager, "Generates pdf document signed with Elhub Certificate")
Rel(GrantManager, MarketParty, "201 Created (documentId)")
Rel(MarketParty, GrantManager, "GET /authorization-documents/{documentId}.pdf")
Rel(GrantManager, MarketParty, "200 OK (document.pdf)")

Rel(MarketParty, SigningService, "Forward document to signing service")
note right
Market Party gets the document signed using an approved certificate authority and signing service .
end note
Rel(EndUser, SigningService, "Signs document")
Rel(SigningService, MarketParty, "Retrieves signed document")

Rel(MarketParty, GrantManager, "PUT /authorization-documents/{documentId}.pdf")
Rel(GrantManager, GrantManager, "Validates signatures in pdf document and creates an AuthorizationGrant")
Rel(GrantManager, MarketParty, "204 - No Content")
Rel(MarketParty, GrantManager, "GET /authorization-documents/{documentId}")
Rel(GrantManager, MarketParty, "200 OK - AuthorizationDocument with relationship reference to AuthorizationGrant")
Rel(MarketParty, EMIF, "Send BRS with authorizationGrantId")

SHOW_LEGEND()
@enduml
