@startuml documents-flow
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Sequence.puml

actor Person_Ext(EndUser, "End User", "")
participant System_Ext(MarketParty, "Market Party", "")
box "Elhub" #LightBlue
  participant System(GrantManager, "auth-grant-manager", "")
  participant System(EMIF, "EMIF", "")
end box

EndUser -> MarketParty: Initiates transaction
MarketParty -> GrantManager: POST /documents
note right
Signed PDF document is generated
end note
GrantManager -> MarketParty: 201 Created (documentId)
MarketParty -> GrantManager: GET /documents/{documentId} (Retrieve)
GrantManager -> MarketParty: 200 OK (document.pdf)
note left
MarketParty shares the document and gets it signed by the EndUser
end note
MarketParty -> GrantManager: PUT /documents/{documentId} (document.pdf)
GrantManager -> MarketParty: 200 OK (consentId)
note right
auth-grant-manager validates the document, creates an AuthorizationGrant and returns the authentificationGrantId.
end note
MarketParty -> EMIF: Send BRS with consentId
note right
EMIF validates the consentId
end note

SHOW_LEGEND()
@enduml
