@startuml dynamic-diagram-request
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/refs/heads/master/C4_Dynamic.puml

Person_Ext(EndUser, "End User", "A person in the power market.")
System_Ext(MarketParty, "Market Party App", "An app or page controlled by an organization participating in the power market.")
System_Boundary(elhub, "Elhub") {
  System(GrantManager, "auth-grant-manager", "The grant manager handles registration and storage of authorization grants in Elhub.")
  System(MyPage, "MinSide", "Minside provides the user interface for End Users that need to interact with Elhub.")
  System(EMIF, "Elhub Machine Interface", "EMIF is the legacy interface for sending/receiving business processes to Elhub.")
}

' Relationships
Rel(EndUser, MarketParty, "Interacts with market party app")
Rel(MarketParty, GrantManager, "Initiates Authorization Request", "HTTPS/JSON")
Rel(MarketParty, MyPage, "Web/App redirects user to MyPage for Authorization", "HTTPS/HTML")
Rel(EndUser, MyPage, "Consents to/Administrates authorization grants", "HTTPS/HTML")
Rel(MyPage, MarketParty, "Redirects back to chosen MarketParty URI", "HTTPS/HTML")
Rel(MarketParty, EMIF, "Sends market processes with valid authorization grant", "HTTPS/SOAP")

SHOW_LEGEND()
@enduml
